name: Notify Slack on Issue
on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "<@U0B2YNTBB0B>\n*${{ github.event.issue.title }}*\n${{ github.event.issue.html_url }}\n\n${{ github.event.issue.body }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}